name: Slow Test

on:
  workflow_dispatch:

jobs:
  slow:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      run: echo "Step 1" && sleep 10
    - name: Step 2
      run: echo "Step 2" && sleep 10
    - name: Done
      run: echo "Finished"
